### ISSUE TITLE
update main.js service

### ISSUE THREAD

**Issue by enlowe** [CoastalResilienceNetwork/water_security#2]
update service (already created) to:
Dev:
http://dev.services.coastalresilience.org:6080/arcgis/rest/services/Water_Blueprint/Source_Protection/MapServer

Production:
http://services.coastalresilience.org:6080/arcgis/rest/services/Water_Blueprint/Source_Protection/MapServer

...following DM protocol

**Comment by cschneebeck** [comment]
Done. Should I close this or is it considered open until the region is built?

**Comment by enlowe** [comment]
thanks Casey. We can just just close them, we're tracking the building of sites outside of git
